server:
  port: 8282

spring:
  application:
    name: 3d-secure-payment
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true

paypal:
  client-id: CLIENT_ID
  client-secret: CLiENT_SECRET
  mode: sandbox # Use 'sandbox' for testing and 'live' production

logging:
  level:
    com.securepayment:
      jdbc:
        core: DEBUG
